### post create user
POST http://{{ origin }}/users
content-type: application/json

{
  "username": "taro"
}

### post create user invalid json
POST http://{{ origin }}/users
content-type: application/json

{
  "username": "taro}

### over Vite proxy
GET http://{{ origin }}/api/json_sample

###
POST http://{{ origin_vite }}/api/todos
content-type: application/json

{
  "text": "Say hello world"
}

###
GET http://{{ origin_vite }}/api/todos

###
GET http://{{ origin_vite }}/api/todos/1


###
PATCH http://{{ origin_vite }}/api/todos/1
content-type: application/json

{
  "text": "say goodbye"
}

###
DELETE http://{{ origin_vite }}/api/todos/10




